Small improvements
nickgaray/osh-docker-template pull request #3
Opened 2024-11-28 21:20 UTC by matthijskooijman

This makes some small improvements. Mostly README improvements or fixes, but also:
 - Changes `docker-compose.yml` to automatically build an image the first time it is started.
 - Adds an `entrypoint.sh` script that fixes permissions, so no manual `chown` is needed anymore.
 - Lets the docker build do a shallow clone, which is more efficient.

Let me know what you think of these, and also the docs updates, since I did throw around a few things.

The "Executing or Running a Docker Container Manually" section in the README is IMHO not very good currently, since it still uses `--mount` instead of `--volume`, uses paths that are no longer really correct, does not show a full working example, and is all the way at the bottom.

I would suggest shortening that section showing mostly just a complete command, and then maybe restructuring the sections to something like:

 1. TL;DR
 2. Cloning this repository
 3. Building & running with docker-compose
 4. Testing deployment
 5. Building manually
 6. Running manually
 7. Understanding docker commands

I've rephrased some of the headings, that is part of the proposal :-)

If this looks good to you, I can add the reordering to the PR (or create new one).

2024-11-30 14:51 UTC, nickgaray requested changes
I appreciate the updates and education; my only comments are around image security and not running image as a privileged user.

2024-11-30 14:51 UTC, nickgaray commented on Dockerfile
> -USER ${USER_UID}:${USER_GID}
From a security perspective the image should not be executed as `root`.  

See: 
https://stackoverflow.com/questions/19054029/security-of-docker-as-it-runs-as-root-user
https://medium.com/@amandubey_6607/container-security-best-practices-avoid-running-containers-as-root-ae37fee2846f

2024-11-30 14:51 UTC, nickgaray commented on entrypoint.sh
> +chown -R "$USER_UID":"$USER_GID" "$OSH_HOME"
I think this goes hand in hand with not allowing the image to execute with a privileged user. See comment on Dockerfile

2024-12-03 10:02 UTC, matthijskooijman commented on Dockerfile
> -USER ${USER_UID}:${USER_GID}
I agree that running the entire container as non-root would be preferred, but AFAICS then there is no way to automatically handle the permission setup. Doing that manually is possible, but more cumbersome and raises the barrier for setting this up quickly (I was also worried that you cannot easily do a manual `chown` on named volumes which are somewhat hidden in `/var/lib/docker/volumes`, but I just tested that docker actually copies the permissions of the directory inside the container to the named volume outside of the container when the volume is created - pity this does not happen for mounted directories when they are created by docker...).

Anyway, also note that with my commit, the application is still not ran as root - the `setpriv` in `entrypoint.sh` drops root privileges after the `chown`, so the application still runs as before, so there should not be significant extra attack surface compared to before (see also https://stackoverflow.com/a/65576874/740048 which analyzes exactly this case).

But it's your call. If you prefer manually setting the permissions, I can drop the commit (and replace it with improving docs on manually setting the permissions). If I've convinced you that the current approach is acceptable in terms of security, then I think no changes are needed.

2024-12-03 18:30 UTC, nickgaray commented on Dockerfile
> -USER ${USER_UID}:${USER_GID}
Considering this is available to the community, if anyone wants to harden the container/image they can undertake specific steps to do so.  For the general user your changes will improve accessability.

2024-12-03 18:31 UTC, merged